variables: &global-variables
  GIT_DEPTH: 10
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"


stages:
  - test
  - pypi

unit_test:
  image: python:latest
  stage: test
  before_script:
    - apt update
    - apt install -y xvfb python-opengl
    - pip install coverage unittest-xml-reporting
  script:
    - pip install .
    - coverage run -m xmlrunner test/gnwrapper.py
    - coverage combine
    - coverage report
  cache:
    paths:
      - "$CI_PROJECT_DIR/.pip"
    key: "${CI_PROJECT_PATH}-TEST"


upload_pypi:
  image: python:latest
  stage: pypi
  before_script:
    - pip install twine wheel
  script:
    - pip wheel --no-deps .
    - twine upload gym_notebook_wrapper-*.whl
  only:
    - tags
  except:
    - branches
    - schedules
  cache:
    paths:
      - "$CI_PROJECT_DIR/.pip"
    key: "${CI_PROJECT_PATH}-PYPI"

