variables: &global-variables
  GIT_DEPTH: 10
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"


stages:
  - build_image
  - test
  - pypi


.docker_build_base: &docker_build
  image: docker:latest
  stage: build_image
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/build:latest || true
    - docker build --pull=true --cache-from $CI_REGISTRY_IMAGE/build:latest -t $CI_REGISTRY_IMAGE/build:latest .
    - docker push $CI_REGISTRY_IMAGE/build:latest

docker_build_schedule:
  <<: *docker_build
  only:
    - schedules

docker_build_manual:
  <<: *docker_build
  when: manual
  except:
    - schedules


unit_test:
  image: $CI_REGISTRY_IMAGE/build:latest
  stage: test
  script:
    - pip install .
    - coverage run -m xmlrunner test/gnwrapper.py
    - coverage combine
    - coverage report


upload_pypi:
  image: $CI_REGISTRY_IMAGE/build:latest
  stage: pypi
  script:
    - pip wheel --no-deps .
    - twine upload gym_notebook_wrapper-*.whl
  only:
    - tags
  except:
    - branches
    - schedules
